logging:
  config: classpath:log4j2.properties
spring:
  application:
    name: BUAA-AIMonkey
buaa:
  programer:
    rootPath: F:/tmp
    target-fitness-count: 0 #最大连续适应度限制
    crossover-rate: 0.7 #交叉概率
    mutationrate: 0.01 #变异概率
    genome-size: 50 #基因序列长度
    max-genome-size: 150 #最大基因长度
    max-iteration-count: 5000 #最大迭代次数
    expand-amount: 0
    expand-rate: 5000
    original-genome-size: 50 #初始基因长度
    population-size: 100 #种群大小
    generation-size: 100000
    target-string: hello
    elitism: true
    adaptive: true #是否开启自适应
    max-fitness: -1 #当前种群最大适应度
    avg-fitness: -1 #当前种群平均适应度
    k1: 0.1
    k2: 0.5
    k3: 0.1
    k4: 0.5
  manager:
    brain-version: 1 #编译器版本
    cross-impl: BinarySinglePoint #[BinarySinglePoint,SinglePoint]
    mutate-impl: OriginMutate #[OriginMutate]
    select-impl: Roulette #[Roulette]
  data-format-pattern: yyyy-MM-dd HH:mm:ss:SSS #时间格式化字符串
